### ISSUE TITLE
fix critical dependencies on the frontend

### ISSUE THREAD

**Issue by vim-usds** [usds/justice40-tool#1498]
# Purpose
Investigate how to address high severity dependabot alerts:

![Screen Shot 2022-03-28 at 8 30 03 AM](https://user-images.githubusercontent.com/86254807/160433608-f9382678-681d-4c25-af4a-658cff1caa2f.png)

## ansi-html

Checking the dependency tree on this:
![Screen Shot 2022-03-28 at 8 32 04 AM](https://user-images.githubusercontent.com/86254807/160433922-99c2cf64-c69f-488d-9ea5-95439f2fc869.png)

If I was working on this, I might look into [moving into Gatsby 4](https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v3-to-v4/).

## node-fetch
Checking the dependency tree on this:
![Screen Shot 2022-03-28 at 8 42 19 AM](https://user-images.githubusercontent.com/86254807/160435972-c7d020d1-705d-453c-bdf7-17fe2d3efe3b.png)

While updating Sentry is easy, I'm wondering why this one is being flagged? The patch is supposedly on [2.6.7](https://github.com/usds/justice40-tool/security/dependabot/21), which is the version we have.  🤔 

## references:
https://github.blog/2022-03-28-how-to-secure-your-end-to-end-supply-chain-on-github/

**Comment by TomNUSDS** [comment]
Step 1 might be to fix dependabot configuration?

I think this is a good start? The dependabot can't seem to find the client `package.json` file?

![dependabot-config-issue.png](https://images.zenhubusercontent.com/6001ffdbfa03b2340a4ca394/32225dd9-1343-4156-9b7f-979995ab7efa)

Seems like the [dependabot.yml](https://github.com/usds/justice40-tool/blob/main/.github/dependabot.yml#L1)  would look more like this: (WARNING: not actually tested)

```yml
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
     allow:
      - dependency-type: "production"
 
  # FRONTEND
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "production"
```

Not sure if "daily" or "weekly" is better? Daily can be a bit noisy.
